### ISSUE TITLE
Cannot load storage module 'Azure' while uploading file to Azure Blob

### ISSUE THREAD

**Issue by hgsongra** [supportify/paperclip-azure#3]
# Paperclip::Errors::StorageMethodNotFound
# Cannot load storage module 'Azure'
# Model Code for upload file Field configuration

has_attached_file :photo, 
       storage: :azure,
                  url: ':azure_path_url',
                  azure_credentials: {
                    storage_account_name: 'NAME',
                    access_key: 'KEY',
                    container: 'CONTAINER'
                  },
                  path: ":class/:id/:filename"
# Gem Versions
- paperclip 4.3.0
- paperclip-optimizer 2.0.0
- image_optim 0.21.0
- waz-storage 1.3.6
- rails 4.2.1

**Comment by medBouzid** [comment]
Is this gem maintained ? I see no one responding to your issue since "jun 26"

**Comment by jordanyaker** [comment]
It is still maintained.  My apologies for a lack of responsiveness.  @medBouzid @HiteshSongra is this a problem for both of you?

**Comment by medBouzid** [comment]
@jordanyaker for me I just want to be sure I can use the gem. also I understand that you are the only maintainer (I think it would be great if we can find some article about how a specific gem is built so we can contribute easily and  help to maintain it :-) 

other than that I wanna ask you about this part object.attachment.expiring_url(30.minutes.since, :thumb) it's not very clear... can you tell me what it does ?

**Comment by jordanyaker** [comment]
@medBouzid I welcome any contributors to this.  In regards, to that line of code, that's how you generate a secure URL for a thumbnail that expires 30 minutes from the time that you generate it.

**Comment by medBouzid** [comment]
@jordanyaker Thank you for your answer but I am not sure where I should use it, also I am not sure what do you mean by "object"

**Comment by jordanyaker** [comment]
The expiring URL is useful when you have links that you want to be secure and that you don't want people sharing; document thumbnails are the easiest example to think of.  

In my example, `object` is simply a generic instance of an entity (e.g.; User, Document, Account, etc.) that a theoretical paperclip resource is attached to.

**Comment by medBouzid** [comment]
Yes I know what SAS means... I read their documentation yesterday :) but where I should put that line of code ? in my model or controller ("new" action)

**Comment by jordanyaker** [comment]
Honestly, I would put that line in a view. It's generating a URL, so that
to me belongs in the view.

If you have view models where a URL is a property, then that might be a
good place too. However, I personally avoid URLs in the controller. But I
think that's more of a Rails philosophy thing and less about this gem.

**Comment by habitullence** [comment]
Any resolution on this issue?
